#!/bin/bash
# Make this app visible to the Fact Explorer running in the taxpert stack, and start that stack if
# it is not already up. Run by `make up`; safe to run on its own, and safe to run twice.
#
# WHY THIS IS NOT A SYMLINK. Fact Explorer discovers apps by globbing `<apps dir>/*/
# fact-explorer.app.json`, and taxpert/apps/README.md offers `ln -s` for exactly that. It works
# natively and fails in Docker: a bind mount carries the symlink itself, not its target, so
# /apps/<app> inside the container is a dangling link and discovery skips it — with no error, just
# an app missing from the menu. A generated app also does not live in taxpert/apps to begin with; it
# lives wherever you were standing when you ran cookiecutter.
#
# So instead this writes a one-service compose fragment into taxpert's docker-compose.apps.d/,
# bind-mounting this repository's real path at /apps-external/<app>. taxpert's Makefile passes every
# fragment in that directory to `docker compose`, and Compose appends the mount to the ones already
# on the fact-explorer service. See docker-compose.apps.d/README.md over there.
#
# /apps-external rather than /apps/<app>, and that is not cosmetic: /apps is a read-only bind mount
# of TAXPERT_APPS_DIR, and a mount nested inside one fails outright — Docker has to create the
# mountpoint, and the parent it must create it in is read-only. Fact Explorer scans both roots
# (FORM_BUILDER_EXTRA_APPS_DIRS, read by appsDirs() in its build-registry.mjs).
#
# Nothing here writes inside this repository, and nothing outside it beyond that one fragment.

set -euo pipefail

APP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APP_ID="{{ cookiecutter.app_id }}"
DEV_PORT="{{ cookiecutter.dev_port }}"

# The taxpert checkout, as answered at generation time (taxpert_repo_path in cookiecutter.json).
# Relative answers are resolved against this repo, not against the caller's cwd.
TAXPERT_REPO="{{ cookiecutter.taxpert_repo_path }}"
case "$TAXPERT_REPO" in
    /*) ;;
    *) TAXPERT_REPO="$APP_DIR/$TAXPERT_REPO" ;;
esac

# Not fatal. Fact Explorer is one of three surfaces this app has, and the other two — the flow itself
# and Author Mode — are served entirely by this repo's own stack. Someone who has not checked out
# taxpert, or who moved it, should still get `make up`.
if [ ! -f "$TAXPERT_REPO/docker-compose.yml" ]; then
    echo "==> no taxpert checkout at $TAXPERT_REPO — skipping Fact Explorer registration"
    echo "    (clone it there, or edit taxpert_repo_path's value into scripts/register-with-taxpert.sh)"
    exit 0
fi

TAXPERT_REPO="$(cd "$TAXPERT_REPO" && pwd)"
FRAGMENT_DIR="$TAXPERT_REPO/docker-compose.apps.d"
FRAGMENT="$FRAGMENT_DIR/$APP_ID.yml"

mkdir -p "$FRAGMENT_DIR"

# Rewritten every time rather than created once, so moving this repository and re-running `make up`
# is all it takes to fix the path. Read-only: Fact Explorer parses the flow and the fact dictionary,
# and the one surface that writes to them is Author Mode, which reaches disk through its own
# container's mount rather than through this one.
cat > "$FRAGMENT" <<YAML
# $APP_ID, mounted for Fact Explorer. Generated by that repo's scripts/register-with-taxpert.sh —
# rewritten on its every \`make up\`, so edit the app, not this file. Delete it to unregister.
services:
  fact-explorer:
    volumes:
      - $APP_DIR:/apps-external/$APP_ID:ro
YAML

echo "==> registered $APP_ID with Fact Explorer ($FRAGMENT)"

# Bring the explorer up, or recreate it if it is already running.
#
# Both cases need the same command. Fact Explorer reads the app list exactly twice, both at
# container start: `npm run make-fgm` writes public/data/apps.json, and vite.config.js builds its
# proxy table from the descriptors it finds. Neither is watched, so a fragment added under a running
# container does nothing at all until the container is recreated — which looks identical to the
# registration having failed. `up -d` recreates on a changed mount set and is a no-op otherwise.
COMPOSE_ARGS=(-f docker-compose.yml -f docker-compose.override.yml)
for fragment in "$FRAGMENT_DIR"/*.yml; do
    [ -f "$fragment" ] && COMPOSE_ARGS+=(-f "$fragment")
done

echo "==> starting Fact Explorer in $TAXPERT_REPO"
if ! (cd "$TAXPERT_REPO" && docker compose "${COMPOSE_ARGS[@]}" --profile explorer up -d fact-explorer); then
    echo "==> could not start Fact Explorer — the rest of this app's stack is unaffected." >&2
    echo "    Try \`make up\` in $TAXPERT_REPO to see why." >&2
    exit 0
fi

echo "==> Fact Explorer: http://localhost:5180/fact-explorer/$APP_ID"
echo "    It proxies this app at http://host.docker.internal:$DEV_PORT, so leave \`make up\` running here."
